---
root: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:react/recommended
  - '@reactnativecommunity'
  - plugin:react-native/all
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
  - react-native
  - jest
settings:
  react:
    version: detect
rules:
  no-console: warn
