endOfLine: lf
tabWidth: 2
semi: true
singleQuote: true
trailingComma: all

overrides:
  - files: '*.json'
    options:
      parser: json
  - files:
    - '*.md'
    - '*.markdown'
    options:
      parser: markdown
  - files:
    - '*.ts'
    - '*.tsx'
    options:
      parser: typescript
  - files:
    - '*.yml'
    - '*.yaml'
    options:
      parser: yaml
